config/routes.rb
Rails.application.routes.draw do
  get '/contact', to: 'home#contact', as: 'contact'
  get '/about', to: 'home#about', as: 'about'
  get '/help', to: 'home#help', as: 'help'
  get '/home', to: 'home#index', as: 'home'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact
  end

  def about
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<% provide(:title, "About") %>

app/views/home/contact.html.erb
<% provide(:title, "Contact") %>

app/views/home/help.html.erb
<% provide(:title, "Help") %>

app/views/home/index.html.erb
<% provide(:title, "Home") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Portafolio </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Home', home_path %>
    <%= link_to 'Contact', contact_path %>
    <%= link_to 'Help', help_path %>
    <%= link_to 'About', about_path %>
    <%= yield %>
  </body>
</html>